name = "Small Iron Pack 3"
author = "taffer3935"
version = "1.3.6"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "630e2cb26261491d4d7b7d06d8b7594166c71f77265c5b2cd7baf0fcea79d976"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
