name = "Small Iron Pack 3"
author = "taffer3935"
version = "1.3.6"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "818a948d6c4a448b467eaccfe79c15a065e578de3333913823b8e330acbb85bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
