[general]
	#The material blacklist of this module. "*" is an alias for all materials, and "*" followed with a material type name is an alias for all materials of that material type. If a material name occurs an odd number of times (including wildcards), then the material is blacklisted. These rules applies to all config material blacklists.
	materialBlacklist = []

#Configurations related to chemical tags.
[chemicalTags]
	#List of infuse type tags that should not be added.
	blacklist = []
	#List of infuse type tags that should be considered as defined.
	customDefined = []
