#General settings
[General]
	#Generate Coal GeOre [Default: true]
	generateCoalGeore = true
	#Generate Copper GeOre [Default: true]
	generateCopperGeore = true
	#Generate Diamond GeOre [Default: true]
	generateDiamondGeore = true
	#Generate Emerald GeOre [Default: true]
	generateEmeraldGeore = true
	#Generate Gold GeOre [Default: true]
	generateGoldGeore = true
	#Generate Iron GeOre [Default: true]
	generateIronGeore = true
	#Generate Lapis GeOre [Default: true]
	generateLapisGeore = true
	#Generate Quartz GeOre [Default: true]
	generateQuartzGeore = true
	#Generate Quartz GeOre in the Nether [Default: true]
	generateQuartzInNetherGeore = true
	#Generate Redstone GeOre [Default: true]
	generateRedstoneGeore = true
	#Disable piston push for budding GeOre (Overrides the vanilla behavior of breaking the block upon being pushed) [Default: false]
	disablePistonPushForBuddingGeOre = false
	#Generate Budding Ancient Debris [Default: true]
	generateBuddingAncientDebris = true

#Modded Generation settings
[ModdedGeneration]
	#Generate Ruby GeOre [Default: false]
	generateRubyGeore = false
	#Generate Sapphire GeOre [Default: false]
	generateSapphireGeore = false
	#Generate Topaz GeOre [Default: false]
	generateTopazGeore = false
	#Generate Zinc GeOre [Default: false]
	generateZincGeore = false
	#Generate Uraninite GeOre [Default: false]
	generateUraniniteGeore = false
	#Generate Black Quartz GeOre [Default: false]
	generateBlackQuartzGeore = false
	#Generate Monazite GeOre [Default: false]
	generateMonaziteGeore = false
	#Generate Aluminum GeOre [Default: false]
	generateAluminumGeore = false
	#Generate Lead GeOre [Default: false]
	generateLeadGeore = false
	#Generate Nickel GeOre [Default: false]
	generateNickelGeore = false
	#Generate Osmium GeOre [Default: false]
	generateOsmiumGeore = false
	#Generate Platinum GeOre [Default: false]
	generatePlatinumGeore = false
	#Generate Silver GeOre [Default: false]
	generateSilverGeore = false
	#Generate Tin GeOre [Default: false]
	generateTinGeore = false
	#Generate Tungsten GeOre [Default: false]
	generateTungstenGeore = false
	#Generate Uranium GeOre [Default: false]
	generateUraniumGeore = false
